apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - flux-system-automation.yaml
  - imagePolicy.yml
  - imageRepository.yml
  - deployment.yaml
  - svc.yml